# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('lang', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(verbose_name='created_at')),
                ('updated_at', models.DateTimeField(verbose_name='updated_at')),
                ('code', models.CharField(max_length=10000)),
                ('slug', models.CharField(max_length=256)),
            ],
        ),
    ]
