# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algo',
            name='slug',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
