# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161203_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='isLang',
            field=models.BooleanField(default=False),
        ),
    ]
