# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161208_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='code',
            name='upvotes',
        ),
    ]
