# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161208_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='code',
            field=models.ManyToManyField(related_name='code_votes', to='main.Code'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
