# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tags_islang'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='id',
            field=models.AutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
